
const INIT_SETUP = 'INIT_SETUP';
const DATA_SETUP = 'DATA_SETUP';
const UPDATE_EVENT = 'UPDATE_EVENT';
const FAVORITE_ADD = 'FAVORITE_ADD';
const FAVORITE_REMOVE = 'FAVORITE_REMOVE';

export const ActionTypes = {
  INIT_SETUP,
  DATA_SETUP,
  UPDATE_EVENT,
  FAVORITE_ADD,
  FAVORITE_REMOVE
};
